/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.openfeed.collectone.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Account service. Represents a row in the &quot;collectone_Account&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.openfeed.collectone.model.impl.AccountModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.openfeed.collectone.model.impl.AccountImpl}.
 * </p>
 *
 * @author sy
 * @see Account
 * @see com.openfeed.collectone.model.impl.AccountImpl
 * @see com.openfeed.collectone.model.impl.AccountModelImpl
 * @generated
 */
public interface AccountModel extends BaseModel<Account> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a account model instance should use the {@link Account} interface instead.
	 */

	/**
	 * Returns the primary key of this account.
	 *
	 * @return the primary key of this account
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this account.
	 *
	 * @param primaryKey the primary key of this account
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the account_id of this account.
	 *
	 * @return the account_id of this account
	 */
	public int getAccount_id();

	/**
	 * Sets the account_id of this account.
	 *
	 * @param account_id the account_id of this account
	 */
	public void setAccount_id(int account_id);

	/**
	 * Returns the company_ ID of this account.
	 *
	 * @return the company_ ID of this account
	 */
	public int getCompany_Id();

	/**
	 * Sets the company_ ID of this account.
	 *
	 * @param company_Id the company_ ID of this account
	 */
	public void setCompany_Id(int company_Id);

	/**
	 * Returns the name of this account.
	 *
	 * @return the name of this account
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this account.
	 *
	 * @param name the name of this account
	 */
	public void setName(String name);

	/**
	 * Returns the first_name of this account.
	 *
	 * @return the first_name of this account
	 */
	@AutoEscape
	public String getFirst_name();

	/**
	 * Sets the first_name of this account.
	 *
	 * @param first_name the first_name of this account
	 */
	public void setFirst_name(String first_name);

	/**
	 * Returns the last_name of this account.
	 *
	 * @return the last_name of this account
	 */
	@AutoEscape
	public String getLast_name();

	/**
	 * Sets the last_name of this account.
	 *
	 * @param last_name the last_name of this account
	 */
	public void setLast_name(String last_name);

	/**
	 * Returns the date of this account.
	 *
	 * @return the date of this account
	 */
	public Date getDate();

	/**
	 * Sets the date of this account.
	 *
	 * @param date the date of this account
	 */
	public void setDate(Date date);

	/**
	 * Returns the active of this account.
	 *
	 * @return the active of this account
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this account is active.
	 *
	 * @return <code>true</code> if this account is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this account is active.
	 *
	 * @param active the active of this account
	 */
	public void setActive(boolean active);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Account account);

	public int hashCode();

	public CacheModel<Account> toCacheModel();

	public Account toEscapedModel();

	public String toString();

	public String toXmlString();
}