/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.openfeed.collectone.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.openfeed.collectone.model.Account;
import com.openfeed.collectone.service.AccountLocalServiceUtil;

/**
 * The extended model base implementation for the Account service. Represents a row in the &quot;collectone_Account&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AccountImpl}.
 * </p>
 *
 * @author sy
 * @see AccountImpl
 * @see com.openfeed.collectone.model.Account
 * @generated
 */
public abstract class AccountBaseImpl extends AccountModelImpl
	implements Account {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a account model instance should use the {@link Account} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			AccountLocalServiceUtil.addAccount(this);
		}
		else {
			AccountLocalServiceUtil.updateAccount(this);
		}
	}
}